"""Write paper/numbers.tex from the sealed result files. Does not refit models."""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper" / "numbers.tex"


def _json(path):
    return json.loads(Path(path).read_text())


def _mae(frame, method, endpoint):
    row = frame[(frame.method == method) & (frame.endpoint == endpoint)]
    return float(row.iloc[0].standardized_mae)


def _num(value, digits=3):
    return f"{float(value):.{digits}f}"


def _p(value):
    value = float(value)
    return "<0.001" if value < 0.001 else f"={value:.3f}"


def main():
    gse_sum = pd.read_csv(ROOT / "runs/cellbridge_v100/gse334503/evaluation/summary.csv")
    em_sum = pd.read_csv(ROOT / "runs/cellbridge_v100/emtab9357/evaluation/summary.csv")
    gse = _json(ROOT / "runs/cellbridge_v100/gse334503/evaluation/decision.json")
    em = _json(ROOT / "runs/cellbridge_v100/emtab9357/evaluation/decision.json")
    gse_freeze = _json(ROOT / "runs/cellbridge_v100/gse334503/freeze.json")
    em_freeze = _json(ROOT / "runs/cellbridge_v100/emtab9357/freeze.json")
    meta = _json(ROOT / "runs/cellbridge_v100/meta/meta.json")
    dev = pd.read_csv(ROOT / "runs/cellbridge_v100/analysis/development/summary.csv")
    sub = pd.read_csv(ROOT / "runs/cellbridge_v100/open_ablations/subgrid_means.csv")
    panel = pd.read_csv(ROOT / "runs/cellbridge_v100/open_ablations/panel_curve.csv")
    sim = _json(ROOT / "runs/cellbridge_v100/open_ablations/simulation.json")
    attr = pd.read_csv(ROOT / "runs/cellbridge_v100/open_ablations/attribution_summary.csv")
    gse_fit = _json(ROOT / "runs/cellbridge_v100/gse334503/fit/fit.json")
    gse_tv = _json(ROOT / "runs/cellbridge_v100/gse334503/totalvi_log.json")
    em_tv = _json(ROOT / "runs/cellbridge_v100/emtab9357/totalvi_log.json")
    lines = [
        "% Generated by scripts/cellbridge_numbers_v100.py. Do not edit by hand.",
        r"\newcommand{\Num}[1]{#1}",
    ]
    macros = {}

    def add(name, text):
        if name in macros:
            raise SystemExit(f"duplicate macro {name}")
        macros[name] = text
        lines.append(f"\\newcommand{{\\{name}}}{{{text}}}")

    roles = {"Gse": gse_freeze["roles"], "Em": em_freeze["groups"]}
    for prefix, role in roles.items():
        add(f"N{prefix}Train", str(len(role["train"])))
        add(f"N{prefix}Cal", str(len(role["calibration"])))
        add(f"N{prefix}Test", str(len(role["test"])))
    methods = {
        "Cb": "cellbridge", "Ab": "v040_abundance_shrinkage", "Tv": "totalvi",
        "Ro": "cellbridge_rna_only", "Jt": "joint_ridge", "Rn": "rna_ridge", "Mn": "mean",
    }
    for cohort, frame in (("Gse", gse_sum), ("Em", em_sum)):
        for code, method in methods.items():
            for endpoint, tag in (("E1_primary", "Eone"), ("E2_all_hidden", "Etwo")):
                hit = frame[(frame.method == method) & (frame.endpoint == endpoint)]
                if len(hit):
                    add(f"Mae{cohort}{code}{tag}", _num(hit.iloc[0].standardized_mae))
    words = ["One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten"]
    for cohort, decision in (("Gse", gse), ("Em", em)):
        for row, word in zip(decision["hypotheses"], words):
            if "mean_difference" not in row:
                continue
            add(f"{cohort}H{word}Gain", _num(row["mean_difference"]))
            add(f"{cohort}H{word}Lo", _num(row["difference_ci95"][0]))
            add(f"{cohort}H{word}Hi", _num(row["difference_ci95"][1]))
            add(f"{cohort}H{word}P", _p(row["sign_flip_p_two_sided"]))
            add(f"{cohort}H{word}Wins", str(row["donor_wins"]))
            add(f"{cohort}H{word}N", str(row["n_donors"]))
            add(f"{cohort}H{word}Tested", "tested" if row.get("tested_in_sequence") else "not tested in sequence")
            add(f"{cohort}H{word}Call", "rejected" if row.get("rejected_null") else "not rejected")
        for row in decision["noninferiority_vs_v040"]:
            tag = "Eone" if row["endpoint"] == "E1_primary" else "Etwo"
            add(f"{cohort}Ni{tag}Upper", _num(row["upper_ci95_excess_loss"]))
            add(f"{cohort}Ni{tag}Hold", "held" if row["noninferior"] else "did not hold")
        cov = decision["conformal"]["cellbridge"]["test_coverage_all_hidden"]
        add(f"{cohort}CovCb", _num(cov))
    add("EmStopped", em.get("sequence_stopped") or "the end of the list")
    add("GseClaim", "supported" if gse["primary_claim_supported"] else "not supported")
    add("EmClaim", "supported" if em["primary_claim_supported"] else "not supported")
    for row in meta["results"]:
        if row["endpoint"] != "E2_all_hidden":
            continue
        code = {"mean": "Mn", "joint_ridge": "Jt", "rna_ridge": "Rn",
                "totalvi": "Tv", "v040_abundance_shrinkage": "Ab"}[row["contrast"]]
        add(f"Meta{code}Fe", _num(row["fixed_effect_mean"]))
        add(f"Meta{code}Se", _num(row["fixed_effect_se"]))
        add(f"Meta{code}Re", _num(row["random_effects"]["mean"]))
        add(f"Meta{code}ReSe", _num(row["random_effects"]["se"]))
    dev_method = {
        "Cb": "cellbridge[shared_top05]", "Ab": "v040_abundance_shrinkage",
        "Jt": "joint_ridge", "Rn": "rna_ridge", "Mn": "mean",
    }
    for code, method in dev_method.items():
        add(f"Dev{code}", _num(dev.loc[dev.method == method, "all_mae"].mean()))
    sub_map = {
        "Full": "cellbridge[shared_top05]",
        "Anchor": "cellbridge[shared_top05|anchors_required]",
        "Kone": "cellbridge[shared_top05|k1]",
        "Rho": "cellbridge[shared_top05|rho0]",
        "Rna": "cellbridge[shared_top05|rna_only]",
    }
    for code, method in sub_map.items():
        add(f"Abl{code}", _num(sub.loc[sub.method == method, "all_mae"].iloc[0]))
    for n, code in ((0, "Zero"), (1, "One"), (2, "Two"), (4, "Four"), (8, "Eight")):
        add(f"Panel{code}", _num(panel.loc[panel.n_anchors == n, "all_mae"].mean()))
    by_sigma = {(row["sigma"], row["grouping"]): row["slope_norm_ratio"] for row in sim["metacells"]}
    add("SimCells", _num(by_sigma[(2.0, "cells")], 2))
    add("SimKmeans", _num(by_sigma[(2.0, "kmeans")], 2))
    add("SimOracle", _num(by_sigma[(2.0, "oracle_states")], 2))
    add("SimCov", _num(sim["conformal"]["coverage"]))
    for _, row in attr.iterrows():
        spelled = {"CD25": "CdTwentyFive", "CD69": "CdSixtyNine", "CD154": "CdOneFiveFour"}
        add(f"Boot{spelled[row.protein]}", _num(100 * row.top_is_anchor, 0))
    add("GseTvCells", f"{gse_tv['training_cells']:,}")
    add("GseTvQuery", f"{gse_tv['query_cells']:,}")
    add("EmTvCells", f"{em_tv['training_cells']:,}")
    add("EmTvGenes", f"{em_tv['genes']:,}")
    if abs(float(em_tv["learning_rate"]) - 4e-4) > 1e-12:
        raise SystemExit("unexpected totalVI learning rate")
    add("EmLr", r"$4\times 10^{-4}$")
    add("GseCbSeconds", _num(gse_fit["timing_seconds"]["cellbridge_fit_seconds"], 1))
    add("GseTvSeconds", _num(gse_tv["fit_seconds"], 0))
    add("GseTvMinutes", _num(gse_tv["fit_seconds"] / 60, 0))
    add("EmTvSeconds", _num(em_tv["fit_seconds"], 0))
    add("EmTvMinutes", _num(em_tv["fit_seconds"] / 60, 0))
    add("ScaleMillionSeconds", _num(next(r["build_seconds"] for r in sim["scaling"] if r.get("n_cells_per_arm") == 1000000), 1))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(macros)} macros to {OUT}")


if __name__ == "__main__":
    main()
